#ifndef APP_WOLFSSL_USER_SETTINGS_H
#define APP_WOLFSSL_USER_SETTINGS_H

#include <zephyr/net/socket.h>

#define WOLFSSL_TLS13
#define HAVE_TLS_EXTENSIONS
#define HAVE_SUPPORTED_CURVES
#define HAVE_ECC
#define HAVE_FFDHE_2048
#define WC_RSA_PSS
#define HAVE_AESGCM
#define HAVE_HKDF
#define HAVE_HASHDRBG
#define WOLFSSL_BASE64_ENCODE
#define WOLFSSL_SHA3
#define WOLFSSL_SHAKE128
#define WOLFSSL_SHAKE256
#define HAVE_SERVER_INDICATION
#define WOLFSSL_SMALL_STACK
#define WOLFSSL_DH_CONST
#define WOLFSSL_NO_SOCK
#define WOLFSSL_USER_IO
#define NO_INT128
#define NO_ASN_TIME_CHECK

#ifdef CONFIG_WOLFSSL_MLKEM
#define WOLFSSL_HAVE_MLKEM
#endif

#endif
