#ifndef APP_WOLFSSL_USER_SETTINGS_H
#define APP_WOLFSSL_USER_SETTINGS_H

#include <zephyr/net/socket.h>

#define WOLFSSL_TLS13
#define WOLFSSL_NO_TLS12
#define NO_OLD_TLS
#define SINGLE_THREADED
#define HAVE_TLS_EXTENSIONS
#define HAVE_SUPPORTED_CURVES
#define HAVE_ECC
#define NO_DH
#define NO_RSA
#define NO_DSA
#define NO_PSK
#define NO_WOLFSSL_SERVER
#define HAVE_AESGCM
#define HAVE_HKDF
#define HAVE_HASHDRBG
#define WOLFSSL_BASE64_ENCODE
#define WOLFSSL_SHA3
#define WOLFSSL_SHAKE128
#define WOLFSSL_SHAKE256
#define HAVE_SERVER_INDICATION
#define WOLFSSL_SMALL_STACK
#define WOLFSSL_DH_CONST
#define NO_SESSION_CACHE
#define WOLFSSL_NO_SOCK
#define WOLFSSL_USER_IO
#define XMALLOC_USER
#define NO_INT128
#define NO_ASN_TIME_CHECK

#ifdef CONFIG_WOLFSSL_MLKEM
#define WOLFSSL_HAVE_MLKEM
#endif

#endif
