#ifndef APP_WOLFMQTT_SETTINGS_H
#define APP_WOLFMQTT_SETTINGS_H

#define ENABLE_MQTT_TLS
#define WOLFMQTT_ZEPHYR
#define WOLFMQTT_NO_STDIO
#define WOLFMQTT_NO_STDIN_CAP
#define WOLFMQTT_NO_ERROR_STRINGS
#define NO_MAIN_DRIVER

#endif
