FROM archlinux:latest

ARG OQS_PREFIX=/opt/oqs
ARG LIBOQS_REF=main
ARG OQS_PROVIDER_REF=main

RUN pacman -Syu --noconfirm && \
    pacman -S --noconfirm --needed \
        autoconf \
        automake \
        base-devel \
        bluez \
        bluez-utils \
        cmake \
        dbus \
        file \
        git \
        iproute2 \
        iputils \
        kmod \
        libtool \
        mosquitto \
        ninja \
        openssl \
        patch \
        pkgconf \
        procps-ng \
        sudo \
        tcpdump \
        util-linux \
        wireshark-cli && \
    pacman -Scc --noconfirm

RUN git clone --depth 1 --branch "${LIBOQS_REF}" https://github.com/open-quantum-safe/liboqs.git /tmp/liboqs && \
    cmake -S /tmp/liboqs -B /tmp/liboqs/build -GNinja \
        -DCMAKE_BUILD_TYPE=Release \
        -DCMAKE_INSTALL_PREFIX="${OQS_PREFIX}" \
        -DBUILD_SHARED_LIBS=ON && \
    cmake --build /tmp/liboqs/build && \
    cmake --install /tmp/liboqs/build && \
    rm -rf /tmp/liboqs

RUN git clone --depth 1 --branch "${OQS_PROVIDER_REF}" https://github.com/open-quantum-safe/oqs-provider.git /tmp/oqs-provider && \
    cmake -S /tmp/oqs-provider -B /tmp/oqs-provider/build -GNinja \
        -DCMAKE_BUILD_TYPE=Release \
        -DCMAKE_INSTALL_PREFIX="${OQS_PREFIX}" \
        -DCMAKE_PREFIX_PATH="${OQS_PREFIX}" \
        -DOPENSSL_ROOT_DIR=/usr \
        -DOPENSSL_MODULES_PATH="${OQS_PREFIX}/lib/ossl-modules" && \
    cmake --build /tmp/oqs-provider/build && \
    cmake --install /tmp/oqs-provider/build && \
    rm -rf /tmp/oqs-provider

COPY docker/server-entrypoint.sh /usr/local/bin/ipsp-server
RUN chmod +x /usr/local/bin/ipsp-server

ENV OQS_PREFIX=${OQS_PREFIX}
ENV OPENSSL_MODULES=${OQS_PREFIX}/lib/ossl-modules
ENV LD_LIBRARY_PATH=${OQS_PREFIX}/lib
ENV ROOT_DIR=/workspace/ipsp_mqtt_tls_wolf
ENV PQC=on
ENV BROKER_KEYLOG=off
ENV MQTT_HOST=127.0.0.1
ENV MQTT_PORT=8883
ENV MQTT_TLS_VERSION=tlsv1.3
ENV NCS_ZEPHYR_DIR=/ncs/v2.6.0/zephyr

WORKDIR /workspace/ipsp_mqtt_tls_wolf
ENTRYPOINT ["/usr/local/bin/ipsp-server"]
CMD ["help"]
